
version: "3.5"

services:
  playedu:
    build: .
    # image: registry.cn-hangzhou.aliyuncs.com/playedu/light:1.5.2
    container_name: playedu-web
    restart: always
    ports:
      - "9805:80"
      - "9806:9800"
      - "9807:9801"
      - "9808:9900"
    volumes:
      - ./playedu-pc:/app  # 映射本地代码到容器内的/app目录
      - ./playedu-admin:/app  # 映射本地代码到容器内的/app目录
      - ./nginx:/var/log/nginx
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=playedu
      - DB_USER=root
      - DB_PASS=playeduxyz
      - REDIS_HOST=redis
      - REDIS_PASS=playeduxyz
      - REDIS_PORT=6379
      - REDIS_DB=2
      - SA_TOKEN_IS_CONCURRENT=false
      - SA_TOKEN_JWT_SECRET_KEY=playeduxyz
       - VITE_DEV=true  # 确保容器运行在开发模式
    command: npm run dev  # 或者是启动 Vite 开发服务器的命令
    depends_on:
      - mysql
      - redis
      - minio

  redis:
    image: redis
    container_name: playedu-redis
    restart: always
    volumes:
      - ./redis:/data

  mysql:
    image: mysql:5.7
    container_name: playedu-mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=playedu
      - MYSQL_ROOT_PASSWORD=playeduxyz
      - TZ=UTC

  minio:
    image: bitnami/minio:latest
    container_name: playedu-minio
    restart: always
    ports:
      - "9809:9000"
      - "9810:9001"
    volumes:
      - ./minio:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=playedu:public